export default {
    tabs: [
        {
            label: "Assigned to me",
            key: "vendor_assign_complete",
            value: 54,
            color: "#EFB608",
        },
        {
            label: "Document Collected",
            key: "document_pickup_complete",
            color: "#ED8020",
            value: 54,
        },
        {
            label: "Service Delivered",
            key: "service_delivery_complete",
            color: "#219653",
            value: 54,
        },
        {
            label: "Service Rejected",
            key: "failed",
            color: "#E22F2F",
            value: 54,
        },
        {
            label: "All Application",
            key: "",
            color: "#2F80ED",
            value: 216,
        },
    ],
    headers: {
        assign_to_me: [
            {
                text_1: "Client Details",
                align: "center",
                sortable: false,
                value: "clientDetail_split",
            },
            {
                text: "Assigned on",
                align: "center",
                sortable: false,
                value: "vendor_assign_date",
            },
            {
                text_1: "Service CATEGORY/",
                text_2: "Application No.",
                align: "center",
                sortable: false,
                value: "service_category_split",
            },
            {
                text: "Address",
                align: "center",
                sortable: false,
                value: "full_address",
            },
            {
                text: "Additional notes",
                align: "center",
                sortable: false,
                value: "additional_note",
            },
            {
                text: "Actions",
                align: "center",
                sortable: false,
                value: "action",
            },
        ],
        document_pickup_complete: [
            {
                text_1: "Client Details/",
                text_2: "Assigned on",
                align: "center",
                sortable: false,
                value: "clientDetail_split",
            },
            {
                text: "Last Update",
                align: "center",
                sortable: false,
                value: "last_updated",
            },
            {
                text_1: "Service CATEGORY/",
                text_2: "Application No.",
                align: "center",
                sortable: false,
                value: "service_category_split",
            },
            {
                text: "Address",
                align: "center",
                sortable: false,
                value: "full_address",
            },
            {
                text: "Additional notes",
                align: "center",
                sortable: false,
                value: "additional_note",
            },
            {
                text: "Current Status",
                align: "center",
                sortable: false,
                value: "current_status",
            },
            {
                text: "Actions",
                align: "center",
                sortable: false,
                value: "action",
            },
        ],
        service_delivery_complete: [
            {
                text_1: "Client Details/",
                text_2: "Assigned on",
                align: "center",
                sortable: false,
                value: "clientDetail_split",
            },
            {
                text: "Last Update",
                align: "center",
                sortable: false,
                value: "last_updated",
            },
            {
                text_1: "Service CATEGORY/",
                text_2: "Application No.",
                align: "center",
                sortable: false,
                value: "service_category_split",
            },
            {
                text: "Address",
                align: "center",
                sortable: false,
                value: "full_address",
            },
            {
                text: "Additional notes",
                align: "center",
                sortable: false,
                value: "additional_note",
            }
        ],
        failed: [
            {
                text_1: "Client Details/",
                text_2: "Assigned on",
                align: "center",
                sortable: false,
                value: "clientDetail_split",
            },
            {
                text: "Last Update",
                align: "center",
                sortable: false,
                value: "last_updated",
            },
            {
                text_1: "Service CATEGORY/",
                text_2: "Application No.",
                align: "center",
                sortable: false,
                value: "service_category_split",
            },
            {
                text: "Address",
                align: "center",
                sortable: false,
                value: "full_address",
            },
            {
                text: "Additional notes",
                align: "center",
                sortable: false,
                value: "additional_note",
            },
            {
                text: "Rejected Reason",
                align: "center",
                sortable: false,
                value: "rejection_reason",
            },
        ],
        all_application: [
            {
                text_1: "Client Details/",
                text_2: "Assigned on",
                align: "center",
                sortable: false,
                value: "clientDetail_split",
            },
            {
                text: "Last Update/ Status",
                align: "center",
                sortable: false,
                value: "last_updated_status",
            },
            {
                text_1: "Service CATEGORY/",
                text_2: "Application No.",
                align: "center",
                sortable: false,
                value: "service_category_split",
            },
            {
                text: "Address",
                align: "center",
                sortable: false,
                value: "full_address",
            },
            {
                text: "Additional notes",
                align: "center",
                sortable: false,
                value: "additional_note",
            },
            {
                text: "Rejected Reason",
                align: "center",
                sortable: false,
                value: "rejection_reason",
            },
        ],
    },
};
